all:
	gcc persistentNumbers.c -o persistentNumbers -L/path/to/libs -lm

test:
	./persistentNumbers 0
	./persistentNumbers 1
	./persistentNumbers 4
	./persistentNumbers 7
	./persistentNumbers 18
	./persistentNumbers 49
	./persistentNumbers 51
	./persistentNumbers 768
	./persistentNumbers -1
