all:
	gcc combinationLock.c -o combinationLock

test:
	./combinationLock 0 30 0 30
	./combinationLock 5 35 5 35
	./combinationLock 0 20 0 20
	./combinationLock 7 27 7 27
	./combinationLock 0 10 0 10
	./combinationLock 9 19 9 19
	./combinationLock 0 0 0 0
	./combinationLock 35 5 35 5